### ISSUE TITLE
`yarn dev` command is not working in Sidecar

### ISSUE THREAD

**Issue by Imod7** [paritytech/substrate-js-dev#128]
#### Issue
[Sidecar](https://github.com/paritytech/substrate-api-sidecar) is using this repo as a dependency and there is one command, `yarn dev`, that is not working anymore with the following error message : 
```
[INFO] 13:13:34 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 5.6.2)
/Users/dominique/Documents/Parity/side-aFresh/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS6053: File '@substrate/dev/config/tsconfig.json' not found.

    at createTSError (/Users/dominique/Documents/Parity/side-aFresh/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/dominique/Documents/Parity/side-aFresh/node_modules/ts-node/src/index.ts:863:19)
    at createFromPreloadedConfig (/Users/dominique/Documents/Parity/side-aFresh/node_modules/ts-node/src/index.ts:874:36)
    at create (/Users/dominique/Documents/Parity/side-aFresh/node_modules/ts-node/src/index.ts:624:10)
    at Object.register (/Users/dominique/Documents/Parity/side-aFresh/node_modules/ts-node/src/index.ts:591:15)
    at registerTsNode (/Users/dominique/Documents/Parity/side-aFresh/node_modules/ts-node-dev/lib/compiler.js:174:16)
    at Object.init (/Users/dominique/Documents/Parity/side-aFresh/node_modules/ts-node-dev/lib/compiler.js:121:9)
    at Object.exports.runDev (/Users/dominique/Documents/Parity/side-aFresh/node_modules/ts-node-dev/lib/index.js:256:14)
    at Object.<anonymous> (/Users/dominique/Documents/Parity/side-aFresh/node_modules/ts-node-dev/lib/bin.js:136:4)
    at Module._compile (node:internal/modules/cjs/loader:1255:14) {
  diagnosticCodes: [ 6053 ]
}
```

#### Suggested Solution
Since the error message is mentioning the current package, `@substrate/dev`, the issue could possibly be resolved by applying some changes in this repo. Maybe if `ts-node` is installed in this repo ([source](https://stackoverflow.com/questions/44764004/ts-node-is-not-recognized-as-an-internal-or-external-command-operable-program)) ?

#### Test
- [ ] Install `ts-node` in this repo
- [ ] Update sidecar to use the version of this repo that has the `ts-node` package installed
- [ ] Test if `yarn dev` is running without issues

**Comment by Imod7** [comment]
Closing since this issue was fixed with this [PR](https://github.com/paritytech/substrate-api-sidecar/pull/1537) from @TarikGul  in Sidecar. 💯
